baseURL = 'https://matthewk88.github.io/hugo-web/'
languageCode = 'en-us'
title = 'My New Hugo Site'


[taxonomies]
  category = "categories"

[outputs]
    home = [ "HTML", "JSON", "RSS"]

paginate = 4